# Generated by Django 6.0.3 on 2026-03-24 07:38

import django.core.validators
import django.db.models.deletion
import myapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occasion', models.CharField(choices=[('wedding', 'Wedding'), ('temple_fair', 'Temple Fair'), ('graduation', 'Graduation'), ('party', 'Party')], max_length=20)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm')], max_length=20)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('metal', 'Metal'), ('jazz', 'Jazz'), ('lofi', 'Lo-fi')], max_length=20)),
                ('requested_duration_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(120, message='Duration must be at least 120 seconds (2 minutes).'), django.core.validators.MaxValueValidator(360, message='Duration must not exceed 360 seconds (6 minutes).')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'generation_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_storage_used', models.FloatField(default=0.0, help_text='Total storage used in MB', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('audio_url', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='myapp.generationrequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='myapp.user')),
            ],
            options={
                'db_table': 'track',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=myapp.models._generate_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='myapp.track')),
            ],
            options={
                'db_table': 'share_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_requests', to='myapp.user'),
        ),
    ]
