# Generated by Django 6.0.4 on 2026-04-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
