# Generated by Django 6.0.4 on 2026-04-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_task_id_to_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='song_title',
            field=models.CharField(blank=True, default='', help_text='Optional song title supplied by the user (SRS FR2.1)', max_length=255),
        ),
    ]
